site_name: Apache and Confluent Flink Studies
repo_url: https://github.com/jbcodeforce/flink-studies.git
site_url: https://jeromeboyer.net/flink-studies
copyright: Copyright &copy; 2018 - 2026 Jerome Boyer
nav:
  - Home: 
    - Introduction: index.md
    - Flink Key Concepts: concepts/index.md
    - Flink SQL concepts: concepts/flink-sql.md
    - Getting started: coding/getting-started.md
    - Flink Architecture: architecture/index.md
    - Fit for purpose: architecture/fitforpurpose.md
    - Labs-Demos: labs/index.md
    - Agentic applications: architecture/agentic_flink.md
  - Recipes:
    - Flink SQL coding:
      - SQL Clients: coding/flink-sql-clients.md
      - Create Table (SQL): coding/flink-sql-1.md
      - SQL DML: coding/flink-sql-2.md
    - Java - Python:
      - Table API: coding/table-api.md
      - DataStreams API: coding/datastream.md
      - UDFs & PTFs: coding/udf_sql.md
    - Deployment: 
      - Sizing: techno/sizing.md
      - Kubernetes Deployment (FKO, CMF): coding/k8s-deploy.md
      - IaC wt Terraform: coding/terraform.md
      - Flink on k8s - Monitoring: techno/fk-k8s-monitor.md
      - Manage CC Flink projects: https://jbcodeforce.github.io/shift_left_utils/
    - More advanced topics:
      - Stateful function: coding/stateful-func.md
      - Complex Event Processing: coding/cep.md
      - Flink Cookbook: architecture/cookbook.md
  - Methodology:
    - Data as a product: methodology/data_as_a_product.md
    - Event Storming: https://jbcodeforce.github.io/eda-studies/methodology/event-storming/
    - Migrate to real-time processing tools: https://jbcodeforce.github.io/shift_left_utils/
    - Center of Excellence: methodology/coe.md
    - A C360 data product demo: https://jbcodeforce.github.io/flink_project_demos/c360/spark_project/
  - Related Technologies:
    - Confluent Cloud Flink: techno/ccloud-flink.md 
    - Confluent Platform for Flink: techno/cp-flink.md 
    - Kafka Integration: architecture/kafka.md
    - Confluent TableFlow: techno/cc-tableflow.md
    - Apache Iceberg: https://jbcodeforce.github.io/techno/data/#data-related-technologies
    - Kafka-studies: https://jbcodeforce.github.io/kafka-studies
  - EDA: https://jbcodeforce.github.io/eda-studies
theme: 
  name: material 
  #logo: images/logo.drawio.png
  logo: images/flink-header-logo.svg
  favicon: images/logo-blue.drawio.png
  palette:
    scheme: default
  language: en
  admonition:
      example: octicons/beaker-16
  features:
      - content.code.annotation
      - content.code.copy
      - content.tooltips
      - content.tabs.link
      - search.suggest
      - search.highlight
      - navigation.instant
      - navigation.instant.progress
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.tracking
      - navigation.sections
      - navigation.expand
      - navigation.top
      - navigation.footer
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - mkdocstrings
  - mermaid2
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - pymdownx.blocks.caption
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.smartsymbols
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/jbcodeforce'
    - icon: fontawesome/brands/linkedin
      link: 'https://linkedin.com/in/jeromeboyer'
    - icon: fontawesome/solid/paper-plane
      mailto: jerome@intelligent-automations.com