apiVersion:   cmf.confluent.io/v1
kind: FlinkApplication
metadata:
  name: rental-dsp
spec:
  image: rental-dsp:latest
  flinkVersion: v2_1
  flinkConfiguration:
      taskmanager.numberOfTaskSlots: "1"
      s3.endpoint: http://minio.minio-dev.svc.cluster.local:9000
      s3.path.style.access: "true"
      s3.connection.ssl.enabled: "false"
      s3.access-key: minioadmin
      s3.secret-key: minioadmin
      state.checkpoints.dir: s3://flink/stateful-flink/checkpoints
      state.savepoints.dir: s3://flink/stateful-flink/savepoints
      state.checkpoints.interval: "10000"
      state.checkpoints.timeout: "600000"
  serviceAccount: flink
  jobManager:
    resource:
      memory: 1024m
      cpu: 1
  taskManager:
    resource:
      memory: 1024m
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/rental-dsp-1.0.0.jar
    entryClass: rental.demo.table.RentalEventsProcessing
    state: running
    parallelism: 1
    upgradeMode: stateless
