scrape_configs:
  - job_name: Confluent Cloud
    scrape_interval: 1m
    scrape_timeout: 1m
    honor_timestamps: true
    static_configs:
      - targets:
        - api.telemetry.confluent.cloud
    scheme: https
    basic_auth:
      username: 
      password:
    metrics_path: /v2/metrics/cloud/export
    params:
      "resource.kafka.id":
        - lkc-3mnm0m
      "resource.schema_registry.id":
        - lsrc-vz1zrz
      "resource.compute_pool.id":
        - lfcp-xvrvmz
        - lfcp-279od2
        - lfcp-oo6doo
        - lfcp-r80731